
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    networks:
      - docker-network
    depends_on:
      - mariadb
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD
      - MARIADB_ADMIN_USER 
      - MARIADB_EMAIL
      - MARIADB_ADMIN_PWD
    volumes: 
      - wp-data:/var/www/html
    networks:
      - docker-network
    restart: always
  
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb 
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD
      - MARIADB_EMAIL
    networks:
      - docker-network
    restart: always

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - docker-network

  grafana:
    build:
      context: ./requirements/bonus/grafana
      dockerfile: Dockerfile
    restart: always
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - docker-network
    volumes:
      - gf-data:/var/www/grafana
  resume:
    build:
      context: ./requirements/bonus/resume
      dockerfile: Dockerfile
    restart: always
    container_name: resume
    ports:
      - "4444:4444"
    networks:
      - docker-network

volumes:

  gf-data:
    driver_opts:
      type: none
      o: bind
      device: /home/asidqi/data/gf-data
  wp-data:
    driver_opts:
      type: none
      o: bind
      device: /home/asidqi/data/wp-data
  mysql:
    driver_opts:
      type: none
      o: bind
      device: /home/asidqi/data/mysql

networks:
  docker-network:
